### ISSUE TITLE
Proper handling of bad ticker searches

### ISSUE THREAD

**Issue by tbryant-tbryant** [rayangendre/Nottingham#27]
StockCheck doesn't have a good default text displaying when a user hasn't searched anything yet, page also needs to be reloaded if an invalid ticker is used. 
Needs error checking and input sanitization before making API call

**Comment by tbryant-tbryant** [comment]
This should apply broadly to the other stock functions, like buy/sell and watchlist. 
Should alert the user when bad search is made
Might need to implement a pre-check before attempting to buy/sell, in order to avoid messing with transaction history (to be added)

**Comment by rayangendre** [comment]
#48 associated to this, more specific to the API call to our external services, read description there
